;проект переработал и собрал BITHACK
[Engine.Engine]
EditorEngine=Editor.EditorEngine

[Core.System]
Paths=../System/*.u

[Editor.EditorEngine]
CacheSizeMegs=32

EditPackages=Core
EditPackages=Engine
EditPackages=NWindow
EditPackages=Interface

;сюда дописываем свои пакеты для компиляции
