@echo off
REM =============================================================
REM  GENERATED BY l2ic -- edits are overwritten by `l2ic kit`.
REM  Builds Interface with the stock UCC kit, via l2.ini.
REM  Output streams to the console AND to Logs\build-Interface-<stamp>.log
REM =============================================================
setlocal
cd /d "%~dp0System"
if not exist "..\Logs" mkdir "..\Logs"
for /f %%t in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd-HHmmss"') do set STAMP=%%t
set LOG=..\Logs\build-Interface-%STAMP%.log

echo.
echo === building Interface ^(log: %LOG%^) ===
REM Every package this ini compiles is removed first: a surviving Engine.u makes
REM UCC re-validate it against Engine.dll and abort.
if exist Core.u del /F /Q Core.u
if exist Engine.u del /F /Q Engine.u
if exist NWindow.u del /F /Q NWindow.u
if exist Interface.u del /F /Q Interface.u
echo N | .\UCC.exe make -NoBind -ini=l2.ini 2>&1 | powershell -NoProfile -Command "$w=[System.IO.StreamWriter]::new('%LOG%',$false,[System.Text.UTF8Encoding]::new($false)); try { $input | ForEach-Object { $_; $w.WriteLine($_) } } finally { $w.Close() }"

findstr /C:"Success -" "%LOG%" >nul
if errorlevel 1 (
    echo.
    echo *** Interface DID NOT BUILD -- see %LOG% ***
    endlocal ^& exit /b 1
)
echo *** Interface.u BUILT ***
REM Collected at the kit root, beside Logs\ -- UCC leaves its output loose in
REM System\ among the toolchain's own packages, where the one file worth keeping
REM is hard to pick out and the next run deletes it.
if not exist "..\Build" mkdir "..\Build"
copy /Y Interface.u "..\Build\Interface.u" >nul
echo     collected to %~dp0Build\Interface.u

echo.
echo Verify before installing -- the rebuilt package carries the toolchain's
echo version, so its profile does not select automatically:
echo     l2ic tokens "%~dp0Build\Interface.u" --profile clients\THIS-CLIENT.profile
endlocal
